#!/bin/sh
set -eu

# Handa one-line installer for macOS / Linux.
#
#   curl -fsSL https://raw.githubusercontent.com/ralphite/handa/main/install.sh | sh
#
# Downloads the self-contained release for this OS/arch (no Python/Node needed),
# unpacks it under ~/.local/share/handa, and links `handa` into ~/.local/bin.
#
# The installed `handa` launcher supervises the server (auto-restart on crash)
# and binds 0.0.0.0 by default so the UI is reachable from other devices on the
# network. Run `handa --host 127.0.0.1` to bind loopback only.
#
# Env overrides:
#   HANDA_REPO     GitHub repo (default: ralphite/handa)
#   HANDA_VERSION  release tag (default: latest)
#   HANDA_HOME     install root (default: ~/.local/share/handa)
#   HANDA_BIN_DIR  where to link the launcher (default: ~/.local/bin)

REPO="${HANDA_REPO:-ralphite/handa}"
VERSION="${HANDA_VERSION:-latest}"
HOME_DIR="${HANDA_HOME:-$HOME/.local/share/handa}"
BIN_DIR="${HANDA_BIN_DIR:-$HOME/.local/bin}"

os="$(uname -s)"
arch="$(uname -m)"
case "$os/$arch" in
  Darwin/arm64)          target="macos-arm64" ;;
  Linux/x86_64|Linux/amd64) target="linux-x86_64" ;;
  Darwin/x86_64)
    echo "No prebuilt binary for Intel Mac (macos-x86_64)." >&2
    echo "Build from source: https://github.com/$REPO#build-from-source" >&2
    exit 1
    ;;
  *)
    echo "Unsupported platform: $os/$arch" >&2
    echo "Handa ships prebuilt for macos-arm64 and linux-x86_64." >&2
    exit 1
    ;;
esac

asset="handa-$target.sh"
if [ "$VERSION" = "latest" ]; then
  url="https://github.com/$REPO/releases/latest/download/$asset"
else
  url="https://github.com/$REPO/releases/download/$VERSION/$asset"
fi

command -v curl >/dev/null 2>&1 || { echo "error: curl is required" >&2; exit 1; }

mkdir -p "$HOME_DIR/releases" "$BIN_DIR"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT INT TERM

echo "Downloading $url"
curl -fSL "$url" -o "$tmp"
chmod +x "$tmp"

echo "Unpacking..."
release_dir="$(sh "$tmp" --extract-only --install-dir "$HOME_DIR/releases")"

# Write a launcher shim rather than a symlink: the bundle's run script locates
# itself via $0, so it must be invoked by its real path. A symlink would make
# run resolve its directory to the symlink's location and miss the runtime.
#
# The shim supervises the server (auto-restart on crash) and binds 0.0.0.0 by
# default so the UI is reachable from other devices on the network.
cat > "$BIN_DIR/handa" <<EOF
#!/bin/sh
# Handa launcher (generated by install.sh).
#
# Supervises the server: a crash triggers an automatic restart after a short
# backoff; a clean exit or Ctrl-C stops it. Binds 0.0.0.0 by default so the UI
# is reachable from other devices on your network. Pass --host explicitly (e.g.
# --host 127.0.0.1) to bind somewhere else.

RUN="$release_dir/run"
HOST="\${HANDA_HOST:-0.0.0.0}"

# Honor a caller-supplied --host/--port instead of forcing our defaults.
inject_host=1
default_port=1
for arg in "\$@"; do
  case "\$arg" in
    --host|--host=*) inject_host=0 ;;
    --port|--port=*) default_port=0 ;;
  esac
done

# Stop the supervision loop on Ctrl-C / SIGTERM instead of relaunching.
trap 'exit 130' INT
trap 'exit 143' TERM

if [ "\$inject_host" = 1 ] && [ "\$HOST" = "0.0.0.0" ]; then
  echo "Handa is binding to 0.0.0.0 (reachable from other devices on your network)."
  if [ "\$default_port" = 1 ]; then
    ip=\$(ipconfig getifaddr en0 2>/dev/null || hostname -I 2>/dev/null | awk '{print \$1}' || true)
    [ -n "\$ip" ] && echo "  Open from another device: http://\$ip:5086"
    echo "  Open locally:             http://127.0.0.1:5086"
  fi
  echo
fi

# Restart on crash, but give up if it keeps dying immediately (bad config, not a
# transient crash) to avoid a tight relaunch loop.
fails=0
while :; do
  start=\$(date +%s 2>/dev/null || echo 0)
  if [ "\$inject_host" = 1 ]; then
    "\$RUN" --host "\$HOST" "\$@"
  else
    "\$RUN" "\$@"
  fi
  status=\$?
  # Clean exit (0) or termination by Ctrl-C (130) / SIGTERM (143): do not relaunch.
  case "\$status" in
    0|130|143) exit "\$status" ;;
  esac
  end=\$(date +%s 2>/dev/null || echo 0)
  if [ "\$((end - start))" -lt 5 ]; then
    fails=\$((fails + 1))
  else
    fails=0
  fi
  if [ "\$fails" -ge 5 ]; then
    echo "handa: server keeps exiting at startup (status \$status); giving up." >&2
    exit "\$status"
  fi
  echo "handa: server exited (status \$status); restarting in 2s..." >&2
  sleep 2
done
EOF
chmod +x "$BIN_DIR/handa"

echo
echo "Handa installed."
echo "  launcher: $BIN_DIR/handa"
echo "  release:  $release_dir"
case ":$PATH:" in
  *":$BIN_DIR:"*) echo "  Run: handa" ;;
  *) echo "  Add $BIN_DIR to your PATH, then run: handa" ;;
esac
